FDC = "ABI-L2-FDCC"
RAD = "ABI-L1b-RadC"
CMI = "ABI-L2-CMIPC"
goes_folder = "GOES"
viirs_folder = "VIIRS"
logs = 'logs'
data_dir = "data"
compare = 'compare'
training = 'training'
compare_dir = "data/$LOC/compare/"
viirs_dir = 'data/$LOC/VIIRS/'
goes_dir = 'data/$LOC/GOES/$PROD/tif/'
training_dir='data/training'
GOES_ndf = 'GOES_netcdfs'
site_conf = 'config/configuration_2019.yml'
toExecuteSiteList = "config/sites_to_run_2019"